// include statements
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "config.h"

#ifndef LASER_H
#define LASER_H

const char *version_num = "0.0.4";

const char *help = "laser usage:\n"
					"\t-v to display version number\n"
					"\t-h to display this message again\n"
					"\t-a followed by a file name to generate a loadable OBJ file\n"
					"\t-c followed by a file name to remove all files generated by '-a'\n";

const char *flags[] = { "-v", "-h", "-a", "-c" };

int checkFlags(char *c);

void parseFile (FILE *fp, char *fname);

int parseArgs(int argc, char **argv);

int main (int argc, char **argv);

#endif