// include statements
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "config.h"

// macros
#define size(arr) ((&arr)[1]-arr)

// version number
const char *version_num = "0.0.4";

// help message
const char *help = "laser usage:\n"
					"\t-v to display version number\n"
					"\t-h to display this message again\n"
					"\t-a followed by a file name to generate a loadable OBJ file\n"
					"\t-c followed by a file name to remove all files generated by '-a'\n";

const char *flags[] = { "-v", "-h", "-a", "-c" };

// function declarations
int checkExt(const char *filename, const char *ext);

char *replaceExt (char *filename, const char *ext);

void parseFile(FILE *fp, char *fname);

int checkFlags(char *c);